name: chat_sdk
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  http: ^1.2.2
  shared_preferences: ^2.3.3
  socket_io_client: ^3.0.1
  video_player: ^2.9.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  audioplayers: ^6.4.0
  file_picker: ^9.0.2
  flutter_sound: ^9.23.1
  permission_handler: ^11.4.0
  open_filex: ^4.7.0

  cupertino_icons: ^1.0.8
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
